### ISSUE TITLE
请问你有对比过Marrying Up Regular Expressions with Neural Networks这篇中attention guide的结果吗

### ISSUE THREAD

**Issue by xyfZzz** [jeffchy/RE2RNN#2]
请问你有对比过Marrying Up Regular Expressions with Neural Networks这篇中attention guide的结果吗？
也就是那篇论文中Network Module Level上+two+both的结果，谢谢~

**Comment by jeffchy** [comment]
你好，没有。paper中也有提过，因为我们FA-RNN没有attention模块，和带attention以及更复杂的模型不可比。
