### ISSUE TITLE
Use my dataset

### ISSUE THREAD

**Issue by Jessiswong** [jeffchy/RE2RNN#3]
Hello, thank you very much for your work, it is very meaningful, but I have some questions to ask you. Can I use my own data set to replace it? And if so, how should I do it? Looking forward to your reply.

**Comment by jeffchy** [comment]
Yes, you can. You need to write your own rules follow the format of the example rule files.
Then you can just follow the pipeline we described in the readme file. Basically, you need to
1. create a new folder for your dataset and place your dataset and rule files as we did for ATIS/TREC/SMS.
2. write the code for creating and loading your new dataset and rules, as we did in data.py and load_data_and_rules.py
https://github.com/jeffchy/RE2RNN/blob/6a5974527dd67bdfe43d5aecb038ecca47f34048/src/data.py#L323 https://github.com/jeffchy/RE2RNN/blob/6a5974527dd67bdfe43d5aecb038ecca47f34048/src/data.py#L343
https://github.com/jeffchy/RE2RNN/blob/6a5974527dd67bdfe43d5aecb038ecca47f34048/src/rules/load_data_and_rules.py#L82
3.then, just follow the pipelines: creating FA, FA to tensor, decomposing tensor, run onehot and decomposed model ... for each step, you need to add several lines of code for your new dataset.

**Comment by Jessiswong** [comment]
Thank you very much for your answer. I will try. But when I reproduced your code, there was always a problem that I couldn't solve. I asked you for help:
When I run the code command python create_automata.py --dataset ATIS --automata_name all --reversed 0
the error will be：
BrokenPipeError：[Broken pipe
![捕获](https://user-images.githubusercontent.com/62866048/110551490-86cc9d00-812d-11eb-9302-9b6d503bb509.JPG)
]

**Comment by Lake-Giotto** [comment]
> Thank you very much for your answer. I will try. But when I reproduced your code, there was always a problem that I couldn't solve. I asked you for help:
> When I run the code command python create_automata.py --dataset ATIS --automata_name all --reversed 0
> the error will be：
> BrokenPipeError：[Broken pipe
> ![捕获](https://user-images.githubusercontent.com/62866048/110551490-86cc9d00-812d-11eb-9302-9b6d503bb509.JPG)
> ]

you need to install the Graphviz
