### ISSUE TITLE
About atis.{}.new.pkl

### ISSUE THREAD

**Issue by Lake-Giotto** [jeffchy/RE2RNN#5]
Hello, thank you very much for your beautiful work. I want to study your paper. I've created the directory as the Readme, but, when I execute "python data.py --dataset ATIS" it throw ERROR:
<img width="560" alt="error" src="https://user-images.githubusercontent.com/35619744/116175123-4dcea300-a742-11eb-87bf-0481fa293766.png">
 I checked the data.py, but I still don't understand what “atis.{}.new.pkl” means.
Waiting for your help, thanks.

**Comment by jeffchy** [comment]
Thanks for your interest, you should download the data.zip we provide (model.zip is also recommended).
