### ISSUE TITLE
关于张量秩分解问题

### ISSUE THREAD

**Issue by wcc17864158993** [jeffchy/RE2RNN#6]
1.当状态数非常大时，比如K=750, 张量秩分解的误差非常大，应该如何解决？
2.当K=750时，我们的rank应该选取多少比较合适？

**Comment by jeffchy** [comment]
K那么大请问是有一个很庞大的规则吗？
据我所知可以选择更大的rank以及对decomposition的过程进行一些调参。
我也不知道K=750需要多少的rank比较合适，由于规则的稀疏性我实验中一般rank和state个数差不多，reconstruction error 在20%以内就有一定效果。
另，可以考虑分成几个小规则set分解然后补成大矩阵。（需要对模型做一些修改，去掉BOS，允许多个start state即可）

**Comment by wcc17864158993** [comment]
> K那么大请问是有一个很庞大的规则吗？
> 据我所知可以选择更大的rank以及对decomposition的过程进行一些调参。
> 我也不知道K=750需要多少的rank比较合适，由于规则的稀疏性我实验中一般rank和state个数差不多，reconstruction error 在20%以内就有一定效果。
> 另，可以考虑分成几个小规则set分解然后补成大矩阵。（需要对模型做一些修改，去掉BOS，允许多个start state即可）
首先，非常感谢您的建议！K很多确实是应为规则数量很多，现有的标签类别数量比较多，每一个类别对应的正则表达式比较复杂，转化为有限状态自动机后，状态数量比较多。

**Comment by jeffchy** [comment]
你好，我们目前的实现是，对于每个类别的正则表达式把他变成一个自动机，对这个小的自动机做minimize。然后将多个小的自动机并联。这样做的目的是，我们能确保每个小自动机的final state不会被merge，防止搞不清楚final state对应的label。
一种可能的处理方式是，对于整个自动机做minimization，但是限制所有的final state不会被merge。这个是可能通过修改minimize的算法实现的。理想情况下会减少很多的state个数。欢迎与我继续讨论这方面的疑问和进展。

**Comment by wcc17864158993** [comment]
> 你好，我们目前的实现是，对于每个类别的正则表达式把他变成一个自动机，对这个小的自动机做minimize。然后将多个小的自动机并联。这样做的目的是，我们能确保每个小自动机的final state不会被merge，防止搞不清楚final state对应的label。
> 一种可能的处理方式是，对于整个自动机做minimization，但是限制所有的final state不会被merge。这个是可能通过修改minimize的算法实现的。理想情况下会减少很多的state个数。欢迎与我继续讨论这方面的疑问和进展。

您好，当规则集合很大的情况下，除了将整个自动机做minimization并限制final state这种方式以为，还有没有可能将规则先划分为几个规则子集，然后将每个子集得到的有限状态自动机wfa转变为一个FA-RNN,得到每个子集的隐藏层输出hi，然后拼接这个hi，再经过一个多层感知机得到最终的预测标签。

**Comment by jeffchy** [comment]
这样是可行的，可以预想到有不错的的初始化结果，并且也可以训练。这是FARNN不作为整体而作为多个子模块进行训练的方式。我们考虑过但没有尝试，这样的不同是每个FARNN的参数是独立的，很难说这是不是一个缺点。
但在K很大的情况下，我觉得这是一个好的方案。
