### ISSUE TITLE
Can you publish the optimal parameter settings on different datasets?

### ISSUE THREAD

**Issue by wcc17864158993** [jeffchy/RE2RNN#7]
Hi, I want to reproduce the results in the paper！So, can you publish the optimal parameter settings on different datasets?

**Comment by jeffchy** [comment]
Hi, thanks for mentioning this, we forgot to add the instructions for checking the hyper-params.
We provide some models **along with their config files**, just see the updated readme (the last part). These files will help you reproduce the results.
